version: "3.8"
services:
  public-health-center-recommendation-redis:
    container_name: public-health-center-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: huijiyoon/public-health-center-recommendation-redis
    ports:
      - "6379:6379"
  public-health-center-recommendation-database:
    container_name: public-health-center-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: huijiyoon/public-health-center-recommendation-database
    environment:
      - MARIADB_DATABASE=public-health-center-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
