spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common
---

spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: 944c4d4eef0d185a196745e7c791ffc6

# ...

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/public-health-center-recommendation
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


---

spring:
  config:
    activate:
      on-profile: prod